theme: jekyll-theme-cayman
show_downloads: true
google_analytics: G-JTBYBEVSLH
github:
  zip_url: https://github.com/jim-breck/FB4/zipball/master
  tar_url: https://github.com/jim-breck/FB4/tarball/master
